title: My Portofolio
author: Juliet
email: julietmaingi1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  La mia fantastica descrizione che andrà qui ;)

# social links
JulietMaingi: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
Juliet-Git:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
